WIP: Add asprintf implementation
IBM/portlibfori pull request #16
Opened 2020-09-16 16:58 UTC by naveen-ram

2020-09-28 23:01 UTC, kadler requested changes

2020-09-28 23:01 UTC, kadler commented on util/build.json
> +            "asprint.h"
```suggestion
            ["stdio.h", "stdio.h"]
```

asprintf and vasprintf are expected to be in [stdio.h](https://man7.org/linux/man-pages/man3/asprintf.3.html), so this header should be named the same.

Please copy what was done for flock in https://github.com/IBM/portlibfori/commit/a0a6b52e637ade3da99247356dd63f7bfffeade3#diff-630f36c8ca89eabc3e205055d1cfc267. You'll need to add the `#include_next` and we should add the `__asm__` bit too, to rename the symbols with the libutil_ prefix.

2020-10-02 01:55 UTC, ThePrez approved these changes

2020-10-12 22:16 UTC, kadler requested changes
Looking pretty good, just a few small things to clean up.

2020-10-12 22:16 UTC, kadler commented on util/asprintf.c
> +    int size = vsnprintf(NULL, 0, format, args);
```suggestion
    int size = vsnprintf(NULL, 0, format, args_copy);
```

2020-10-12 22:16 UTC, kadler commented on util/asprintf.c
> +        return -1
```suggestion
        return -1;
```

2020-10-12 22:16 UTC, kadler commented on util/stdio.h
> +/* it contains - just override flock */
Looks like this comment needs to be adjusted since it still references sys/file.h and flock.

2020-10-12 22:16 UTC, kadler commented on util/libutil.exp
> +vasprintf
These need the libutil_ prefix to match the function definitions.

2020-10-16 15:34 UTC, kadler approved these changes
LGTM

2020-10-16 15:35 UTC, merged